-- Create the scrape_results table
create table if not exists public.scrape_results (
    id bigint generated by default as identity primary key,
    scraped_at timestamp with time zone not null default now(),
    data jsonb not null,
    created_at timestamp with time zone not null default now()
);

-- Set up Row Level Security (RLS)
alter table public.scrape_results enable row level security;

-- Create a policy that allows all operations for authenticated users
create policy "Allow all operations for authenticated users"
    on public.scrape_results
    for all
    to authenticated
    using (true)
    with check (true);

-- Create a policy that allows only read operations for anonymous users
create policy "Allow read-only access for anonymous users"
    on public.scrape_results
    for select
    to anon
    using (true); 